/**
 * Autogenerated by Thrift Compiler (0.7.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package cn.com.cloudstone.menu.server.thrift.api;

import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * 订单
 */
public class Order implements org.apache.thrift.TBase<Order, Order._Fields>, java.io.Serializable, Cloneable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("Order");

  private static final org.apache.thrift.protocol.TField GOODS_FIELD_DESC = new org.apache.thrift.protocol.TField("goods", org.apache.thrift.protocol.TType.LIST, (short)1);
  private static final org.apache.thrift.protocol.TField ORIGINAL_PRICE_FIELD_DESC = new org.apache.thrift.protocol.TField("originalPrice", org.apache.thrift.protocol.TType.DOUBLE, (short)2);
  private static final org.apache.thrift.protocol.TField PRICE_FIELD_DESC = new org.apache.thrift.protocol.TField("price", org.apache.thrift.protocol.TType.DOUBLE, (short)3);
  private static final org.apache.thrift.protocol.TField REMARKS_FIELD_DESC = new org.apache.thrift.protocol.TField("remarks", org.apache.thrift.protocol.TType.STRING, (short)4);
  private static final org.apache.thrift.protocol.TField TABLE_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("tableId", org.apache.thrift.protocol.TType.STRING, (short)5);

  public List<GoodsOrder> goods; // required
  public double originalPrice; // required
  public double price; // required
  public String remarks; // required
  public String tableId; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    GOODS((short)1, "goods"),
    ORIGINAL_PRICE((short)2, "originalPrice"),
    PRICE((short)3, "price"),
    REMARKS((short)4, "remarks"),
    TABLE_ID((short)5, "tableId");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // GOODS
          return GOODS;
        case 2: // ORIGINAL_PRICE
          return ORIGINAL_PRICE;
        case 3: // PRICE
          return PRICE;
        case 4: // REMARKS
          return REMARKS;
        case 5: // TABLE_ID
          return TABLE_ID;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __ORIGINALPRICE_ISSET_ID = 0;
  private static final int __PRICE_ISSET_ID = 1;
  private BitSet __isset_bit_vector = new BitSet(2);

  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.GOODS, new org.apache.thrift.meta_data.FieldMetaData("goods", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, GoodsOrder.class))));
    tmpMap.put(_Fields.ORIGINAL_PRICE, new org.apache.thrift.meta_data.FieldMetaData("originalPrice", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.DOUBLE)));
    tmpMap.put(_Fields.PRICE, new org.apache.thrift.meta_data.FieldMetaData("price", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.DOUBLE)));
    tmpMap.put(_Fields.REMARKS, new org.apache.thrift.meta_data.FieldMetaData("remarks", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.TABLE_ID, new org.apache.thrift.meta_data.FieldMetaData("tableId", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(Order.class, metaDataMap);
  }

  public Order() {
  }

  public Order(
    List<GoodsOrder> goods,
    double originalPrice,
    double price,
    String remarks,
    String tableId)
  {
    this();
    this.goods = goods;
    this.originalPrice = originalPrice;
    setOriginalPriceIsSet(true);
    this.price = price;
    setPriceIsSet(true);
    this.remarks = remarks;
    this.tableId = tableId;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public Order(Order other) {
    __isset_bit_vector.clear();
    __isset_bit_vector.or(other.__isset_bit_vector);
    if (other.isSetGoods()) {
      List<GoodsOrder> __this__goods = new ArrayList<GoodsOrder>();
      for (GoodsOrder other_element : other.goods) {
        __this__goods.add(new GoodsOrder(other_element));
      }
      this.goods = __this__goods;
    }
    this.originalPrice = other.originalPrice;
    this.price = other.price;
    if (other.isSetRemarks()) {
      this.remarks = other.remarks;
    }
    if (other.isSetTableId()) {
      this.tableId = other.tableId;
    }
  }

  public Order deepCopy() {
    return new Order(this);
  }

  @Override
  public void clear() {
    this.goods = null;
    setOriginalPriceIsSet(false);
    this.originalPrice = 0.0;
    setPriceIsSet(false);
    this.price = 0.0;
    this.remarks = null;
    this.tableId = null;
  }

  public int getGoodsSize() {
    return (this.goods == null) ? 0 : this.goods.size();
  }

  public java.util.Iterator<GoodsOrder> getGoodsIterator() {
    return (this.goods == null) ? null : this.goods.iterator();
  }

  public void addToGoods(GoodsOrder elem) {
    if (this.goods == null) {
      this.goods = new ArrayList<GoodsOrder>();
    }
    this.goods.add(elem);
  }

  public List<GoodsOrder> getGoods() {
    return this.goods;
  }

  public Order setGoods(List<GoodsOrder> goods) {
    this.goods = goods;
    return this;
  }

  public void unsetGoods() {
    this.goods = null;
  }

  /** Returns true if field goods is set (has been assigned a value) and false otherwise */
  public boolean isSetGoods() {
    return this.goods != null;
  }

  public void setGoodsIsSet(boolean value) {
    if (!value) {
      this.goods = null;
    }
  }

  public double getOriginalPrice() {
    return this.originalPrice;
  }

  public Order setOriginalPrice(double originalPrice) {
    this.originalPrice = originalPrice;
    setOriginalPriceIsSet(true);
    return this;
  }

  public void unsetOriginalPrice() {
    __isset_bit_vector.clear(__ORIGINALPRICE_ISSET_ID);
  }

  /** Returns true if field originalPrice is set (has been assigned a value) and false otherwise */
  public boolean isSetOriginalPrice() {
    return __isset_bit_vector.get(__ORIGINALPRICE_ISSET_ID);
  }

  public void setOriginalPriceIsSet(boolean value) {
    __isset_bit_vector.set(__ORIGINALPRICE_ISSET_ID, value);
  }

  public double getPrice() {
    return this.price;
  }

  public Order setPrice(double price) {
    this.price = price;
    setPriceIsSet(true);
    return this;
  }

  public void unsetPrice() {
    __isset_bit_vector.clear(__PRICE_ISSET_ID);
  }

  /** Returns true if field price is set (has been assigned a value) and false otherwise */
  public boolean isSetPrice() {
    return __isset_bit_vector.get(__PRICE_ISSET_ID);
  }

  public void setPriceIsSet(boolean value) {
    __isset_bit_vector.set(__PRICE_ISSET_ID, value);
  }

  public String getRemarks() {
    return this.remarks;
  }

  public Order setRemarks(String remarks) {
    this.remarks = remarks;
    return this;
  }

  public void unsetRemarks() {
    this.remarks = null;
  }

  /** Returns true if field remarks is set (has been assigned a value) and false otherwise */
  public boolean isSetRemarks() {
    return this.remarks != null;
  }

  public void setRemarksIsSet(boolean value) {
    if (!value) {
      this.remarks = null;
    }
  }

  public String getTableId() {
    return this.tableId;
  }

  public Order setTableId(String tableId) {
    this.tableId = tableId;
    return this;
  }

  public void unsetTableId() {
    this.tableId = null;
  }

  /** Returns true if field tableId is set (has been assigned a value) and false otherwise */
  public boolean isSetTableId() {
    return this.tableId != null;
  }

  public void setTableIdIsSet(boolean value) {
    if (!value) {
      this.tableId = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case GOODS:
      if (value == null) {
        unsetGoods();
      } else {
        setGoods((List<GoodsOrder>)value);
      }
      break;

    case ORIGINAL_PRICE:
      if (value == null) {
        unsetOriginalPrice();
      } else {
        setOriginalPrice((Double)value);
      }
      break;

    case PRICE:
      if (value == null) {
        unsetPrice();
      } else {
        setPrice((Double)value);
      }
      break;

    case REMARKS:
      if (value == null) {
        unsetRemarks();
      } else {
        setRemarks((String)value);
      }
      break;

    case TABLE_ID:
      if (value == null) {
        unsetTableId();
      } else {
        setTableId((String)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case GOODS:
      return getGoods();

    case ORIGINAL_PRICE:
      return Double.valueOf(getOriginalPrice());

    case PRICE:
      return Double.valueOf(getPrice());

    case REMARKS:
      return getRemarks();

    case TABLE_ID:
      return getTableId();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case GOODS:
      return isSetGoods();
    case ORIGINAL_PRICE:
      return isSetOriginalPrice();
    case PRICE:
      return isSetPrice();
    case REMARKS:
      return isSetRemarks();
    case TABLE_ID:
      return isSetTableId();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof Order)
      return this.equals((Order)that);
    return false;
  }

  public boolean equals(Order that) {
    if (that == null)
      return false;

    boolean this_present_goods = true && this.isSetGoods();
    boolean that_present_goods = true && that.isSetGoods();
    if (this_present_goods || that_present_goods) {
      if (!(this_present_goods && that_present_goods))
        return false;
      if (!this.goods.equals(that.goods))
        return false;
    }

    boolean this_present_originalPrice = true;
    boolean that_present_originalPrice = true;
    if (this_present_originalPrice || that_present_originalPrice) {
      if (!(this_present_originalPrice && that_present_originalPrice))
        return false;
      if (this.originalPrice != that.originalPrice)
        return false;
    }

    boolean this_present_price = true;
    boolean that_present_price = true;
    if (this_present_price || that_present_price) {
      if (!(this_present_price && that_present_price))
        return false;
      if (this.price != that.price)
        return false;
    }

    boolean this_present_remarks = true && this.isSetRemarks();
    boolean that_present_remarks = true && that.isSetRemarks();
    if (this_present_remarks || that_present_remarks) {
      if (!(this_present_remarks && that_present_remarks))
        return false;
      if (!this.remarks.equals(that.remarks))
        return false;
    }

    boolean this_present_tableId = true && this.isSetTableId();
    boolean that_present_tableId = true && that.isSetTableId();
    if (this_present_tableId || that_present_tableId) {
      if (!(this_present_tableId && that_present_tableId))
        return false;
      if (!this.tableId.equals(that.tableId))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public int compareTo(Order other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    Order typedOther = (Order)other;

    lastComparison = Boolean.valueOf(isSetGoods()).compareTo(typedOther.isSetGoods());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetGoods()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.goods, typedOther.goods);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetOriginalPrice()).compareTo(typedOther.isSetOriginalPrice());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetOriginalPrice()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.originalPrice, typedOther.originalPrice);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetPrice()).compareTo(typedOther.isSetPrice());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPrice()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.price, typedOther.price);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetRemarks()).compareTo(typedOther.isSetRemarks());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetRemarks()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.remarks, typedOther.remarks);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetTableId()).compareTo(typedOther.isSetTableId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTableId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.tableId, typedOther.tableId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    org.apache.thrift.protocol.TField field;
    iprot.readStructBegin();
    while (true)
    {
      field = iprot.readFieldBegin();
      if (field.type == org.apache.thrift.protocol.TType.STOP) { 
        break;
      }
      switch (field.id) {
        case 1: // GOODS
          if (field.type == org.apache.thrift.protocol.TType.LIST) {
            {
              org.apache.thrift.protocol.TList _list4 = iprot.readListBegin();
              this.goods = new ArrayList<GoodsOrder>(_list4.size);
              for (int _i5 = 0; _i5 < _list4.size; ++_i5)
              {
                GoodsOrder _elem6; // required
                _elem6 = new GoodsOrder();
                _elem6.read(iprot);
                this.goods.add(_elem6);
              }
              iprot.readListEnd();
            }
          } else { 
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 2: // ORIGINAL_PRICE
          if (field.type == org.apache.thrift.protocol.TType.DOUBLE) {
            this.originalPrice = iprot.readDouble();
            setOriginalPriceIsSet(true);
          } else { 
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 3: // PRICE
          if (field.type == org.apache.thrift.protocol.TType.DOUBLE) {
            this.price = iprot.readDouble();
            setPriceIsSet(true);
          } else { 
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 4: // REMARKS
          if (field.type == org.apache.thrift.protocol.TType.STRING) {
            this.remarks = iprot.readString();
          } else { 
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 5: // TABLE_ID
          if (field.type == org.apache.thrift.protocol.TType.STRING) {
            this.tableId = iprot.readString();
          } else { 
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
          }
          break;
        default:
          org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
      }
      iprot.readFieldEnd();
    }
    iprot.readStructEnd();

    // check for required fields of primitive type, which can't be checked in the validate method
    validate();
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    validate();

    oprot.writeStructBegin(STRUCT_DESC);
    if (this.goods != null) {
      oprot.writeFieldBegin(GOODS_FIELD_DESC);
      {
        oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, this.goods.size()));
        for (GoodsOrder _iter7 : this.goods)
        {
          _iter7.write(oprot);
        }
        oprot.writeListEnd();
      }
      oprot.writeFieldEnd();
    }
    oprot.writeFieldBegin(ORIGINAL_PRICE_FIELD_DESC);
    oprot.writeDouble(this.originalPrice);
    oprot.writeFieldEnd();
    oprot.writeFieldBegin(PRICE_FIELD_DESC);
    oprot.writeDouble(this.price);
    oprot.writeFieldEnd();
    if (this.remarks != null) {
      oprot.writeFieldBegin(REMARKS_FIELD_DESC);
      oprot.writeString(this.remarks);
      oprot.writeFieldEnd();
    }
    if (this.tableId != null) {
      oprot.writeFieldBegin(TABLE_ID_FIELD_DESC);
      oprot.writeString(this.tableId);
      oprot.writeFieldEnd();
    }
    oprot.writeFieldStop();
    oprot.writeStructEnd();
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("Order(");
    boolean first = true;

    sb.append("goods:");
    if (this.goods == null) {
      sb.append("null");
    } else {
      sb.append(this.goods);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("originalPrice:");
    sb.append(this.originalPrice);
    first = false;
    if (!first) sb.append(", ");
    sb.append("price:");
    sb.append(this.price);
    first = false;
    if (!first) sb.append(", ");
    sb.append("remarks:");
    if (this.remarks == null) {
      sb.append("null");
    } else {
      sb.append(this.remarks);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("tableId:");
    if (this.tableId == null) {
      sb.append("null");
    } else {
      sb.append(this.tableId);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bit_vector = new BitSet(1);
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

}

