/**
 * Autogenerated by Thrift Compiler (0.7.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package cn.com.cloudstone.menu.server.thrift.api;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

/**
 * 餐桌状态。已预订，已占用，空置。
 */
public enum TableStatus implements org.apache.thrift.TEnum {
  Ordered(0),
  Occupied(1),
  Empty(2);

  private final int value;

  private TableStatus(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static TableStatus findByValue(int value) { 
    switch (value) {
      case 0:
        return Ordered;
      case 1:
        return Occupied;
      case 2:
        return Empty;
      default:
        return null;
    }
  }
}
