/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package cn.com.cloudstone.menu.server.thrift.api;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

/**
 * 页面布局类型
 * 每一页的布局方式，后面的数字表示此页的菜的数量。
 * 比如 Triangle4，页面三角形布局，此页4个菜。
 */
public enum PageLayoutType implements org.apache.thrift.TEnum {
  Horizontal1(0),
  Horizontal2(1),
  Horizontal3(2),
  Triangle4(3),
  Grid6(4);

  private final int value;

  private PageLayoutType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static PageLayoutType findByValue(int value) { 
    switch (value) {
      case 0:
        return Horizontal1;
      case 1:
        return Horizontal2;
      case 2:
        return Horizontal3;
      case 3:
        return Triangle4;
      case 4:
        return Grid6;
      default:
        return null;
    }
  }
}
